version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run:
          name: Install sentry-cli
          command: curl -sL https://sentry.io/get-cli/ | bash
      - run:
          name: Print sentry-cli version
          command: sentry-cli --version
