version: 2
jobs:
  build:
    macos:
      xcode: '9.0'
    steps:
      - checkout
      - run:
          name: Install sentry-cli
          command: npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
