version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-23-alpha
    steps:
      - checkout
      - run:
          name: Install node js
          command: curl --silent --location https://deb.nodesource.com/setup_8.x | sudo bash - && sudo apt-get install -y nodejs
      - run:
          name: Install sentry-cli
          command: npm install sentry-cli-binary
      - run:
          name: Print sentry-cli version
          command: node_modules/.bin/sentry-cli --version
